# Generated by Django 5.0.2 on 2024-03-01 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fast_butoontext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fast',
            old_name='butoonText',
            new_name='buttonText',
        ),
    ]
